  <div class="overlay2">
    <div class="container">
        <div class="row fw-header">
            <ul class="nav nav-pills" id="navbar">
                <li class="{% if page.nav == 'Home' %}active{% endif %}"><a href="/">Home</a></li>
                <li class="{% if page.nav == 'Workshops' %}active{% endif %}"><a href="/workshops.html">Workshops</a></li>
                <li class="{% if page.nav == 'Materials' %}active{% endif %}"><a href="/materials.html">Books and talks</a></li>
                <li class="{% if page.nav == 'Testimonials' %}active{% endif %}"><a href="/testimonials.html">Testimonials</a></li>
                <li class="{% if page.nav == 'Partners' %}active{% endif %}"><a href="/partners.html">Partners</a></li>
                <li class="{% if page.nav == 'Team' %}active{% endif %}"><a href="/team.html">About us</a></li>
            </ul>
        </div>
    </div>
  </div>
